#!/usr/bin/env python3
"""
Download Inter and JetBrains Mono once and serve them from this domain.

Why: a <link> to fonts.googleapis.com makes every visitor's browser contact
Google before the page can render, and it sends the visitor's IP address there.
German courts have treated exactly that as a data protection violation
(LG München I, 3 O 17493/20, 20 January 2022), and it is the reason this repo
carries no third-party requests at all. Self-hosting also removes a render-
blocking round trip to a foreign origin.

What the script does:

  1. asks the Google Fonts CSS API for the two families as variable fonts,
  2. keeps the latin and latin-ext subsets (everything this site needs,
     including German umlauts and the Czech, Polish and Turkish spellings
     that appear in author names),
  3. downloads each .woff2 into assets/fonts/,
  4. writes the @font-face rules into assets/style.css, between

         /* BEGIN fonts */
         /* END fonts */

     so there is no extra HTTP request for a second stylesheet.

Run it once, commit assets/fonts/ together with the changed assets/style.css.
It only needs Python 3 and the standard library. Re-run it to pick up a new
font release; the output is deterministic, so an unchanged upstream produces
an unchanged diff.

Both families are licensed under the SIL Open Font License 1.1, which permits
redistribution; the licence text is written to assets/fonts/OFL.txt.

Usage:
    python3 tools/fetch_fonts.py
"""

import pathlib
import re
import sys
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "assets" / "fonts"
CSS = ROOT / "assets" / "style.css"

BEGIN = "/* BEGIN fonts */"
END = "/* END fonts */"

API = ("https://fonts.googleapis.com/css2"
       "?family=Inter:wght@400..700"
       "&family=JetBrains+Mono:wght@400..600"
       "&display=swap")

# Without a modern browser User-Agent the API answers with .ttf instead of the
# much smaller .woff2.
UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36")

KEEP_SUBSETS = {"latin", "latin-ext"}

LICENCE_URL = "https://raw.githubusercontent.com/rsms/inter/master/LICENSE.txt"


def get(url, binary=False):
    request = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(request, timeout=30) as response:
        payload = response.read()
    return payload if binary else payload.decode("utf-8")


def blocks(css):
    """Yield (subset, block) pairs. Google labels each block with a comment."""
    subset = None
    for chunk in re.split(r"(/\*\s*[a-z0-9-]+\s*\*/)", css):
        label = re.fullmatch(r"/\*\s*([a-z0-9-]+)\s*\*/", chunk.strip())
        if label:
            subset = label.group(1)
        elif subset and "@font-face" in chunk:
            for face in re.findall(r"@font-face\s*\{.*?\}", chunk, re.S):
                yield subset, face


def slug(text):
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def main():
    try:
        css = get(API)
    except OSError as err:
        sys.exit("could not reach the Google Fonts API: %s\n"
                 "The script needs network access once; nothing else in this "
                 "repository does." % err)

    OUT.mkdir(parents=True, exist_ok=True)
    faces, kept, skipped = [], 0, 0

    for subset, face in blocks(css):
        if subset not in KEEP_SUBSETS:
            skipped += 1
            continue
        family = re.search(r"font-family:\s*'([^']+)'", face).group(1)
        url = re.search(r"url\((https://[^)]+\.woff2)\)", face)
        if not url:
            sys.exit("unexpected API answer: no .woff2 in a @font-face block.\n"
                     "Google may have changed the format; check the block:\n%s" % face)

        name = "%s-%s.woff2" % (slug(family), subset)
        (OUT / name).write_bytes(get(url.group(1), binary=True))
        faces.append(face.replace(url.group(1), "/assets/fonts/" + name))
        kept += 1

    if not faces:
        sys.exit("no usable @font-face blocks came back — aborting rather than "
                 "writing an empty font block into assets/style.css.")

    faces.sort()
    block = "%s\n/* Generated by tools/fetch_fonts.py. Do not edit by hand. */\n%s\n%s" % (
        BEGIN, "\n".join(faces), END)

    text = CSS.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        sys.exit("markers %s / %s not found in assets/style.css" % (BEGIN, END))
    text = text[:text.index(BEGIN)] + block + text[text.index(END) + len(END):]
    CSS.write_text(text, encoding="utf-8")

    try:
        (OUT / "OFL.txt").write_text(get(LICENCE_URL), encoding="utf-8")
    except OSError:
        print("note: could not fetch the OFL licence text — add it by hand")

    total = sum(f.stat().st_size for f in OUT.glob("*.woff2"))
    print("downloaded %d font files (%.0f KB total), skipped %d unused subsets"
          % (kept, total / 1024.0, skipped))
    for f in sorted(OUT.glob("*.woff2")):
        print("  %-34s %5.0f KB" % (f.name, f.stat().st_size / 1024.0))
    print("wrote the @font-face rules into assets/style.css")
    print("\nNow: python3 tools/check_site.py && git add assets/fonts assets/style.css")


if __name__ == "__main__":
    main()
